# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

namespace:
  enabled: false
  name: firoportal
  limits:
    cpu: '3'
    memory: 6Gi
    ephemeral_storage: '10Gi'
  requests:
    cpu: '3'
    memory: 6Gi
    ephemeral_storage: '10Gi'

image:
  repository: "ghcr.io/firo-tethys/tethys_portal_firo"
  tag: main
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

postgis:
  fullnameOverride: "db"
  postgres_user: "postgres"
  postgres_password: "please_dont_use_default_passwords"
  extra_config:
    max_connections: "500"
    shared_buffers: "512MB"
    work_mem: "5MB"
    autovacuum: "on"
  service:
    type: ClusterIP
    port: 5432
  storage_size: 5Gi
  resources: 
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 4
      memory: 4Gi

redis:
  enabled: true
  fullnameOverride: 'redis'
  architecture: standalone
  auth:
    enabled: false

tethys:
  workspace_size: "5Gi"
  settings:
    asgi_processes: 4
    tethys_settings_flags: "--production, --overwrite, --bypass-portal-home"
    channel_layers_backend: 'channels_redis.core.RedisChannelLayer'
    portal_title: "Aquaveo Portal"
    primary_color: "#256291"
    secondary_color: "#7C99AC"
    background_color: "#D7D3C7"
    client_max_body_size: "1G"
    file_upload_max_memory_size: "1073741824"
    data_upload_max_memory_size: "1073741824"
    copyright: "Copyright © 2023 Aquaveo, LLC"
    bing_api_key: ""
    recaptcha_public_key: ""
    recaptcha_private_key: ""
    app_installer_user_email: ""
    app_installer_user_name: ""
  database:
    tethys_db_name: "tethys_platform"
    tethys_db_username: "tethys_default"
    tethys_db_password: "please_dont_use_default_passwords"
    tethys_db_superuser: "tethys_super"
    tethys_db_superuser_pass: "please_dont_use_default_passwords"
  super_user:
    username: "admin"
    password: "pass"
    email: "none@none.com"
  updateStrategy: "Recreate"
  apps:
    app_store:
      custom_settings:
        encryption_key: "please_dont_use_default_passwords"
        stores_settings: 
          stores:
            - conda_channel: "conda_channel"
              conda_labels:
                - main
              github_organization: "github_organization"
              github_token: "ecrpyted_github_token"
              default: true

service:
  type: ClusterIP
  port: 80

# Note: The first host in the ingress field is used as TETHYS_PUBLIC_HOST and TETHYS_GS_HOST_PUB. 
# This is true EVEN IF the ingress is not enabled!
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: localhost
  tls: []

resources: 
 requests:
   cpu: 2
   memory: 2Gi
 limits:
   cpu: 2
   memory: 3Gi

nodeSelector: {}
tolerations: []
affinity: {}
